# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve [--baseurl '']'. If you change this file, please restart the server process.

title: heatherlauren.me
email: hello@heatherlauren.me
description: Hi, I'm Heather
baseurl: ""
url: "http://heatherlauren.github.io"
permalink: pretty

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
plugins:
    - jekyll-minifier
jekyll-minifier:
  exclude: ["assets/css/*.css","*.min.*"]
